### PR TITLE
fixed 'examples_enabled' variable from not being read

### PR DESCRIPTION
**Pull request by builderjer**
This fixes issue [#26 ].  Not sure why I can't import from `idleRoot`

### CODE REVIEW

**Review by AIIX — COMMENTED** [review]
Please remove cache files

**Comment by builderjer** [comment]
I think I did [here](https://github.com/OpenVoiceOS/skill-ovos-homescreen/pull/34/commits/670db32688202950065b2918d7c4b75e2cd17bdb)

**Comment by AIIX** [comment]
There are still 3 cache files that need to be removed apart from pycache folder

**Comment by builderjer** [comment]
Didn't realize those were there.  Done

**Pull request merged**
