### PR TITLE
Added config option for US version of MDY

### PR DESCRIPTION
**Pull request by builderjer**
Gives the option in `mycroft.conf` to add `"date_format": "MDY-us"
Makes it more grammatically correct for US english

### CODE REVIEW

**Comment by builderjer** [comment]
This corresponds to [this](https://github.com/OpenVoiceOS/skill-homescreen-lite/pull/1/commits/11ebd8b9d24e5801d6bb090367efd28bed1fdcb9) commit in [skill-ovos-homescreen-lite](https://github.com/OpenVoiceOS/skill-homescreen-lite)

**Comment by NeonDaniel** [comment]
I wonder if MDY should have this behavior rather than another variant? Is there a locale that writes "September Wed 07, 2022" or is it a leftover from the previous default format (DMY) "Wed 07 September 2022"

**Comment by JarbasAl** [comment]
This variant wont be recognized in other core places, its not officially supported in core and changing it in mycroft.conf may cause unexpected breakage when if comparisons start failing. Should this be default for MDY instead?

**Comment by NeonDaniel** [comment]
> This variant wont be recognized in other core places, its not officially supported in core and changing it in mycroft.conf may cause unexpected breakage when if comparisons start failing. Should this be default for MDY instead?

I think this should be default MDY since I assume the US user base would be the largest using MDY format and this is the format used here. I agree adding variants will probably break other things that just do string comparisons

**Pull request merged**
